---
title: "p8105_hw1_hn2339"
author: Haowei Ni 
date: 09/18/2018
output: github_document
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Problem 1 
```{r HW1_problem1}
library(tidyverse)
problem1_df = tibble (
# random sample of size 10 from unifom distrubution [0,5]
sample_random = runif(10, min = 0, max = 5),
# whether the elements from the sample > 2 
logical_vector = sample_random > 2,
# create a character vector length of 10
character = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
# create a factor vector lenght of 10
me.vector = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
factor.me.vector = factor(me.vector),
)
# take the mean of the variable 
mean(problem1_df$sample_random)
#take the mean of logical vector 
mean(problem1_df$logical_vector)
# can not determine the mean because character vector is not numcerial or logical
mean(problem1_df$character)
# cannot take the mean of factor vector because it is not numerical or logical 
mean(problem1_df$me.vector)
```

```{r results ='hide'}
# convert logical variables to numeric 
as.numeric(problem1_df$logical_vector)
# convert character variables to numeric 
as.numeric(problem1_df$character)
# convert factor variables to numberic 
as.numeric(problem1_df$me.vector)
```

```{r}
# conver character to factor to numeric is successful 
character_factor_numeric = as.factor(problem1_df$character)
as.numeric(character_factor_numeric)
# convert factor to character is successful but character to numeric is not successful 
factor_character = as.character(problem1_df$me.vector)
as.numeric(factor_character)
```

#Problem 2 
```{r HW1_problem2}
#from the environment, the size of plot_df is 1000, the mean of x is - 0.01164814 the median of x is -0.03532423, 49% of the logical vector is true 
set.seed(1)
library(tidyverse)
plot_df = tibble(
  x = rnorm(1000, mean = 0, sd = 1),
  y = rnorm(1000, mean = 0, sd = 1),
  vector_logical = c(x + y > 0),
  typeof(vector_logical),
  median(x),
  mean(x),
  n = as.numeric(vector_logical),
  f = as.factor(vector_logical)
) 
  
ggplot(plot_df, aes(x = x, y = y, color = vector_logical )) + geom_point()
ggsave("plot_df.pdf")
ggplot(plot_df, aes(x = x, y = y, col = n )) + geom_point()
ggplot(plot_df, aes(x = x, y = y, col = f )) + geom_point()

```
#The size of plot_df is `r dim(plot_df$x)`, the mean of x is `r mean(plot_df$x)`, the median of x is `r median(plot_df$x)`, 49% of the logical vector is true `r mean(plot_df$vector_logical)`

